HashingHub
OriginTrail/dkg-evm-module pull request #10
Opened 2022-11-10 20:16 UTC by u-hubar

- HashingHub contract
- HashingAlgorithm interface
- SHA256 contract implementation

2022-11-10 20:30 UTC, zeroxbt approved these changes

2022-11-11 12:37 UTC, branarakic requested changes

2022-11-11 14:21 UTC, u-hubar commented on contracts/HashingHub.sol
> +import { HashingAlgorithm } from "./interface/HashingAlgorithm.sol";
Done

2022-11-11 14:21 UTC, u-hubar commented on contracts/interface/HashingAlgorithm.sol
> +interface HashingAlgorithm {
Done

2022-11-11 14:23 UTC, u-hubar commented on contracts/HashingHub.sol
> +        algorithms[hashingAlgorithmId] = hashingContractAddress;
Done

2022-11-11 14:44 UTC, u-hubar commented on contracts/hashing/sha256.sol
> +
Done

2022-11-11 15:20 UTC, merged